# Generated by Django 5.0.3 on 2024-03-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_matrix_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='start_matrix',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='matrix_data',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
